Import the numpy package under the name np and Print the numpy version and the configuration 

In [3]:
import numpy as np
print (np.__version__)
np.show_config()

1.17.0
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ishwarya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Ishwarya/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Ishwarya/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\wind

Create a null vector of size 10

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Create Simple 1-D array and check type and check data types in array

In [10]:
b = np.array([1,2,3,4,5])
print (type(b))
print (b)
print (b.dtype)

<class 'numpy.ndarray'>
[1 2 3 4 5]
int32


How to find number of dimensions, bytes per element and bytes of memory used?

In [12]:
print (b.ndim)
print (b.size)
print (b.itemsize)

1
5
4


Create a null vector of size 10 but the fifth value which is 1

In [13]:
a = np.zeros(10)
a[5] = 1
print (a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


Create a vector with values ranging from 10 to 49

In [14]:
c = np.arange(10,49)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

Reverse a vector (first element becomes last)

In [17]:
print (c[::-1])
print (np.flipud(c))

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
d = np.arange(0,9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Find indices of non-zero elements from [1,2,0,0,4,0]

In [20]:
e = [1,2,0,0,4,0]
np.nonzero(e)

(array([0, 1, 4], dtype=int64),)

Create a 3x3 identity matrix

In [21]:
f = np.identity(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a 3x3x3 array with random values

In [22]:
g = np.arange(0,27).reshape(3,3,3)
g

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Create a 10x10 array with random values and find the minimum and maximum values

In [25]:
g = np.arange(0,100).reshape(10,10)
print (np.min(g))
print (np.max(g))

0
99


Create a random vector of size 30 and find the mean value

In [26]:
print (np.mean(g))

49.5


Create a 2d array with 1 on the border and 0 inside

In [34]:
h = np.ones((5,5))     
h[1:-1,1:-1] =0
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

How to add a border (filled with 0's) around an existing array? 

In [42]:
i = np.ones((3,3))
print (i)
i = np.pad(i,pad_width=1,mode='constant',constant_values=0)
i

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

How to Accessing/Changing specific elements, rows, columns, etc in Numpy array?

Example -
[[ 1 2 3 4 5 6 7] [ 8 9 10 11 12 13 14]]

Get 13, get first row only, get 3rd column only, get [2, 4, 6], replace 13 by 20

In [69]:
j = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print (j[1][5])
print (j[1])
print (j[:,3])
print (j[0::2])
print (np.where(j==13,20,j))

13
[ 8  9 10 11 12 13 14]
[ 4 11]
[[1 2 3 4 5 6 7]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


How to Convert a 1D array to a 2D array with 2 rows

In [71]:
k = np.arange(20).reshape(2,10)
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input:

a = np.array([1,2,3])`
Desired Output:

#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [76]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,5)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3])

Write a program to show how Numpy taking less memory compared to Python List?

In [83]:
import sys 

l = [1,2,3,4,5]
larray = np.array(l)
print (sys.getsizeof(l))
print (larray.size * larray.itemsize)

104
20


Write a program to show how Numpy taking less time compared to Python List?